display:
  default:
    display_title: الرئيسي
    display_options:
      fields:
        id:
          label: 'المعرف ID'
          separator: ', '
        parent_id:
          label: الأب
          separator: ', '
        parent_type:
          separator: ', '
        status:
          label: منشور
          separator: ', '
        type:
          label: النوع
          separator: ', '
        nothing:
          label: إجراء
          alter:
            text: حذف
            alt: حذف
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      filters:
        type:
          expose:
            label: النوع
