display:
  default:
    display_title: الرئيسي
    display_options:
      title: الاعضاء
      fields:
        name:
          label: المستخدم
          separator: ', '
        group_roles:
          label: الأدوار
          separator: ', '
        changed:
          label: التحديث
          separator: ', '
        created:
          separator: ', '
        dropbutton:
          label: عمليات
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      arguments:
        gid:
          exception:
            title: الكل
  page_1:
    display_title: الصفحة
    display_options:
      menu:
        title: الاعضاء
