ocha_docstore_files.settings:
  type: config_object
  label: 'Docstore settings'
  mapping:
    endpoint_url:
      type: string
      label: 'Docstore URL'
    endpoint_apikey:
      type: string
      label: 'API key'
