display:
  default:
    display_title: Máster
    display_options:
      title: Nodos
      fields:
        title:
          label: Título
          separator: ', '
        type:
          label: 'Tipo de contenido'
          separator: ', '
        status:
          label: Estado
          settings:
            format_custom_false: 'Sin publicar'
            format_custom_true: Publicado
          separator: ', '
        changed:
          label: Actualizado
          separator: ', '
        dropbutton:
          label: Operaciones
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'No hay contenido disponible.'
      arguments:
        gid:
          exception:
            title: Todo(s)
          title: '{{ arguments.gid|placeholder }} pages'
      filters:
        status:
          expose:
            label: 'Estado de publicación'
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
              2:
                title: 'Sin publicar'
        type:
          expose:
            label: Tipo
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Nodos
