label: 'Group members'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        name:
          label: Usuario
          separator: ', '
        group_roles:
          label: Roles
          separator: ', '
        changed:
          label: Actualizado
          separator: ', '
        created:
          label: Joined
          separator: ', '
        edit_group_content:
          text: 'Edit member'
        delete_group_content:
          text: 'Remove member'
        dropbutton:
          label: Operaciones
      arguments:
        gid:
          exception:
            title: Todo(s)
      title: Members
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Members
