label: 'Group nodes'
display:
  default:
    display_title: Maître
    display_options:
      title: Nœuds
      fields:
        title:
          label: Titre
          separator: ', '
        type:
          label: 'Type de contenu'
          separator: ', '
        status:
          label: État
          settings:
            format_custom_false: 'Non publié'
            format_custom_true: Publié
          separator: ', '
        changed:
          label: 'Mis à jour'
          separator: ', '
        view_group_content:
          label: 'Link to Group content'
        edit_group_content:
          label: 'Link to edit Group content'
          text: 'Edit relation'
        delete_group_content:
          label: 'Link to delete Group content'
          text: 'Delete relation'
        edit_node:
          text: 'Edit node'
        delete_node:
          text: 'Delete node'
        dropbutton:
          label: Actions
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'Aucun contenu disponible.'
      arguments:
        gid:
          exception:
            title: Tout
          title: '{{ arguments.gid|placeholder }} pages'
      filters:
        status:
          expose:
            label: 'Statut de publication'
          group_info:
            label: 'Statut de publication'
            group_items:
              1:
                title: Publié
              2:
                title: 'Non publié'
        type:
          expose:
            label: Type
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Nœuds
