label: 'Group members'
display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        name:
          label: Utilisateur
          separator: ', '
        group_roles:
          label: Rôles
          separator: ', '
        changed:
          label: 'Mis à jour'
          separator: ', '
        created:
          label: Joined
          separator: ', '
        edit_group_content:
          text: 'Edit member'
        delete_group_content:
          admin_label: 'Remove member link'
        dropbutton:
          label: Actions
      arguments:
        gid:
          exception:
            title: Tout
      title: Members
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Members
