_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  masquerade__unmasquerade:
    menu_name: account
    parent: user.page
    weight: -49
    expanded: false
    enabled: false
  hr_paragraphs__unmasquerade:
    menu_name: account
    parent: user.page
    weight: -50
    expanded: false
    enabled: true
  user__logout:
    menu_name: account
    parent: ''
    weight: -46
    expanded: false
    enabled: true
  user__page:
    menu_name: account
    parent: ''
    weight: -47
    expanded: false
    enabled: true
