_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  masquerade__unmasquerade:
    weight: -49
    parent: ''
    menu_name: account
    expanded: false
    enabled: false
  hr_paragraphs__unmasquerade:
    parent: user.page
    menu_name: account
    enabled: true
    expanded: false
    weight: -50
  user__logout:
    weight: -47
    parent: ''
    menu_name: account
    expanded: false
    enabled: true
  user__page:
    weight: -48
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
