always_save_userinfo: true
connect_existing_users: false
override_registration_settings: true
end_session_enabled: true
user_login_display: replace
redirect_login: ''
redirect_logout: ''
userinfo_mappings: {  }
role_mappings:
  administrator: {  }
  global_editor: {  }
