_core:
  default_config_hash: PeDvVH4C3IZ7QFkvC1BUv3BZJVc7jLwQmJAEttVuVOw
frequency: 172800
offset: 604800
user_expire_roles:
  authenticated: 2592000
  content_editor: 2592000
  administrator: 2592000
  hr_info_admin: 2592000
