azure_tweaks.settings:
  type: config_object
  label: 'Azure tweaks settings'
  mapping:
    password_url:
      type: string
      label: 'Password reset url'
    register_url:
      type: string
      label: 'Register URL'
    openid_connect_client:
      type: string
      label: 'OpenID Client'
